### ISSUE TITLE
github webhook "ping" request kills molybdenum

### ISSUE THREAD

**Issue by trentm** [trentm/molybdenum#13]
```
^[[32m[2014-03-20 20:00:17.598] [INFO] console - ^[[39mXXX github payload:  '{\n    "zen": "Non-blocking is better than blocking.",\n    "hook_id": 1979334\n}'

/root/services/molybdenum.old/app.js:210
      repoName = data.repository.name;
                                ^
TypeError: Cannot read property 'name' of undefined
    at Object.<anonymous> (/root/services/molybdenum.old/app.js:210:33)
    at nextMiddleware (/root/services/molybdenum.old/node_modules/express/lib/router/index.js:139:34)
    at IncomingMessage.<anonymous> (/root/services/molybdenum.old/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:74:9)
    at IncomingMessage.emit (events.js:61:17)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at Socket.ondata (http.js:1019:22)
    at Socket._onReadable (net.js:683:27)
    at IOWatcher.onReadable [as callback] (net.js:177:10)
[ Mar 20 20:00:17 Stopping because all processes in service exited. ]
[ Mar 20 20:00:18 Executing stop method (:kill). ]
[ Mar 20 20:00:19 Executing start method ("/opt/node/0.4.9/bin/node /root/services/molybdenum.old/app.js &"). ]
[ Mar 20 20:00:19 Method "start" exited with status 0. ]
```

**Comment by trentm** [comment]
I believe this was fixed in commit d86c6010750b281ac20a5e6caaded12a92446347
